### ISSUE TITLE
Migrate algorithm section to Implementation Guide

### ISSUE THREAD

**Issue by reece** [ga4gh/vr-spec#134]
We currently have an "Algorithm" section. Refactor as "Implementation Guide", then include (at least):

- [x] #126: distinguish serialization types
- [x] #128: document use of native identifiers
- [x] #129: write namespace proposal in appendix
- [x] #133: defined data proxy requirements

These issues are being subsumed in one issue because they must work together as a coherent presentation.

**Comment by reece** [comment]
Status:
* Renamed Algorithm section to Implement Guidance
* Closed #126: distinguish serialization types
* Closed #133: added section on external data requirements (sequences and sequence accessions)
* Merged Serialization + Digest + Computed Identifiers into one page and significantly improved discussion
* Closed #129: Wrote computed identifier proposal appendix.
* Added Glossary

Although some of these topics need refinement, I think this body of work is now ready for merging and subsequent tweaking.

**Comment by ahwagner** [comment]
I think that efb8922 handles a very challenging situation well by constructing the GA4GH Namespace Proposal as an appendix, and referencing the situation with a note at the top of _Computed Identifiers_. I would, however, change the subsection _Plan B_ to a more descriptive heading, such as _Alternative Namespace_.

**Comment by reece** [comment]
@ahwagner I agree. Will do.

**Comment by reece** [comment]
Q for crew: I'm a bit concerned that the IG section mixes normative elements (e.g., normalization) that are *requirements* with informational elements (e.g., required data) that aid with understanding but aren't requirements. As you read the current spec, please consider this question.

@rrfreimuth @larrybabb: You two have a lot of experience reading specs. Any comments on current structure with regard to the above, or suggestions for what to do?
