### ISSUE TITLE
Respond to Aug 15 PRC comments

### ISSUE THREAD

**Issue by reece** [ga4gh/vr-spec#160]
- [x] In principles, mention value object principle → VR objects are NOT containers; data should be associated with objects, not embedded within them.
- [x] Clarify Important not re: computed identifiers requiring ga4gh sequence identifiers
- [x] ~#161: Either clarify _digest and _id usage, or enable underscore-prefixed attributes~
- [x] #162: Clarify _digest and _id usage
- [x] #159: Add complete HGVS-to-VR example  
- [ ] Respond to comments in the [VR PRC Reviewer Google Doc](https://docs.google.com/document/d/1TkgJMttPjKuAwc86B5x6jWw6HP-6waJyZmi7LFq5oYs/edit)

### Underscore-prefixed extension attributes:
For the underscore-prefixed attributes, the proposal is:
- drop _id and _digest from the schema since they exist purely as implementation conveniences (and are overly specific as well)
- permit *any* underscore-prefixed attribute. Use is implementation-defined. Underscore attributes are NOT included in digest serialization (as-is requirement).
- add new requirement that underscore attributes be excluded from messages

This would be very easy to implement and would allow us to drop _id and _digest from the information model, which I think makes sense.

**Comment by reece** [comment]
Many comments in the Google doc were addressed. Most were left open for administrative closure.
Otherwise, all items on this issue are now complete. Closing.
