### ISSUE TITLE
Final PRC response actions

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vr-spec#165]
For our final release candidate before sending to the Steering Committee, we intend to implement the following changes:

- [x] @ahwagner, @reece: [DONE](https://github.com/ga4gh/vr-spec/commit/3578aff42c60592581867f3224f201bbe02a42b6). Revise and publish the HGVS "how-to" guide suggested by @julesjacobsen in https://github.com/ga4gh/vr-spec/issues/164#issue-481560744.
- [x] @ahwagner: [DONE](https://github.com/ga4gh/vr-spec/commit/ff1a6c93739f5dcd97fbcea5648fe18a933484fb). Move the examples from the appendices to the implementation guide section as suggested by @julesjacobsen in https://github.com/ga4gh/vr-spec/issues/164#issuecomment-521974746.
- [x] @ahwagner: [DONE](https://github.com/ga4gh/vr-spec/commit/549f8fdb1955825649c45bc95ed2b69fe289122d). Loosen requirements on the `_id` attribute to allow for _any_ CURIE, instead of VR _only_ CURIEs, in response to comments from @briandoconnor and @larrybabb. Addresses #141.
- [x] @ahwagner: [DONE](https://github.com/ga4gh/vr-spec/commit/358cca02082111d57f0fdb7dcfae388201792aa3). Update documentation and examples to reflect loss of `_digest` attribute
- [x] @reece: Adapt vr-python to not need `_digest` attribute 
- [x] @reece: Regenerate all notebooks without `_digest`.
- [x] @reece: [DONE](https://github.com/ga4gh/vr-spec/commit/31f744ea50b88124b55ecd8e76af328cff85816d) Remove the `_digest` attribute from vr.yaml, which is a convenience slot for implementations and is not necessary for messaging.
- [x] @reece: [DONE](https://github.com/ga4gh/vr-spec/commit/7236d4edc07bb11d48e361e7e7adce620a549cf3). Replace recommendation for implementers to define valid Location / State combinations with a recommendation for implementers to do validation and sanity checking, as proposed by @melissacline in the email below:

> **Terminology -> Allele -> Implementation guidance**
> “Implementations MAY choose to provide a mechanism for ensuring that the type of sequence and the content of the state are compatible, but such behavior is not provided by the specification.”
> Minor clarification needed here.  I believe that what this means to say is that the application may choose a validation and error handling mechanism, rather than the application defining which types of sequence and state are compatible.   Is that correct?

**Comment by ahwagner** [comment]
To my knowledge, @reece will be handling bullet 5 above (validation recommendation).
I will start by working on bullets 3 and 4 (`_id` and `_digest` changes).

**Comment by larrybabb** [comment]
@reece just to make sure it doesn't slip through the cracks. please make sure to remove the `_digest` from the [associating annotations example section](https://github.com/ga4gh/vr-spec/blob/1.0rc/docs/source/appendices/examples/associating-annotations.rst) as well.

(for later)
I'd also like to ask if we should add the `_id` into this annotation example (or maybe as an alternative implementation that is more supportive of a JSON-LD approach?

**Comment by reece** [comment]
@larrybabb: How much later? I created #166 to track this request separately.

**Comment by reece** [comment]
@melissacline:  I addressed your comments regarding error handling and namespaces in [7236d4e](https://github.com/ga4gh/vr-spec/commit/7236d4edc07bb11d48e361e7e7adce620a549cf3). Would you please review the following?

* [3rd bullet (Error handling is intentionally...)](https://vr-spec.readthedocs.io/en/1.0rc/terms_and_model.html#data-model-notes-and-principles)
* [Implementation Guidance for CURIEs](https://vr-spec.readthedocs.io/en/1.0rc/terms_and_model.html#curie) for namespace options.

As you'll see from the namespace discussion, we do not consider VR as having purview over which namespace an implementation supports. The spec intentionally covers only abstract external data requirements. The existing Required Data section is descriptive, not normative, so I don't see how we can require any particular behavior there. I *do* agree that standardizing such an interface would be very useful, but it's beyond our scope.

Does all of these meet your requests?

**Comment by reece** [comment]
@ahwagner: I dropped _digest from the schema and limited references in docs. I also dropped the B64UDigest type. Please see updated checklist above.

https://github.com/ga4gh/vr-spec/commit/31f744ea50b88124b55ecd8e76af328cff85816d

**Comment by ahwagner** [comment]
@reece: tracking my status in top-level comment, good system! Tackling item 2 (examples to implementation guide) next.

**Comment by reece** [comment]
Grabbing lunch, then continuing vr-python work.

**Comment by ahwagner** [comment]
Daycare had a power outage, so I'm done for the day. Realistically, will complete the work from #167 by Monday afternoon, earlier if time allows.

**Comment by reece** [comment]
Whoops. We finished this work long ago!
